"""Play against the trained network in a window (Arcade).

The same weights the trainer writes are used here: whatever `make train`
produced under ``runs/<name>/checkpoints`` is loaded through the usual backend
selection, so this runs on CUDA, on Apple MLX, on Metal via PyTorch MPS, or on
the CPU without any change to this file.

Run it with ``make gui`` (see ``omok gui --help`` for the options).  The search
lives on a worker thread -- see :mod:`omok.engine` -- and this module only
draws and collects input.  The easing curves and the particle pool live in
:mod:`omok.effects`; the art in ``omok/assets`` is generated by
``tools/make_assets.py``.

Everything visual degrades: if the assets are missing the board falls back to
flat colours, and ``f`` turns the effects off entirely.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass, replace

try:
    import arcade
except ImportError as exc:  # pragma: no cover - depends on the environment
    raise ImportError(
        "the Arcade GUI needs the `arcade` package -- run `make install-gui`"
    ) from exc

from arcade.types import Color

from .board import BLACK, Board, DIRECTIONS, EMPTY, WHITE, board_from_moves, format_move
from .config import Config
from .effects import (Animated, Clip, Particles, clamp, ease_in_out_cubic,
                      ease_out_back, ease_out_cubic, ease_out_elastic, ease_out_quad,
                      mix, pulse)
from .engine import Engine

ASSET_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")

# ---------------------------------------------------------------- palette
WOOD = (216, 178, 126)
WOOD_EDGE = (120, 88, 52)
GRID = (64, 48, 34)
BLACK_STONE = (26, 26, 30)
WHITE_STONE = (243, 241, 236)
STONE_EDGE = (38, 38, 42)
# Tints for textured draws; arcade wants a real Color here, not a tuple.
SHADOW = Color(40, 26, 14)
PANEL_TINT = Color(150, 155, 170)
PANEL_BG = (23, 25, 30)
PANEL_RULE = (46, 50, 59)
TEXT = (228, 232, 240)
TEXT_DIM = (136, 145, 160)
ACCENT = (110, 175, 255)
GOOD = (122, 202, 142)
WARN = (232, 178, 92)
MONO = ("Menlo", "DejaVu Sans Mono", "Consolas", "monospace")

# Spark colours: warm for a black stone, cool for a white one, so a burst reads
# as belonging to the stone that caused it.
SPARK_BLACK = (255, 176, 72)
SPARK_WHITE = (168, 226, 255)
CONFETTI = ((255, 196, 84), (120, 226, 168), (128, 186, 255), (255, 132, 148),
            (245, 240, 214))

# Difficulty presets bound to the number keys.
LEVELS = ((1, "beginner", 24), (2, "casual", 100), (3, "strong", 320), (4, "max", 900))
# The four ways the two colours can be shared between human and engine.
MODES = ("black", "white", "none", "both")
MODE_LABELS = {"black": "you play black", "white": "you play white",
               "none": "engine vs engine", "both": "two humans"}


def human_colours(mode: str) -> frozenset[int]:
    return {
        "black": frozenset({BLACK}),
        "white": frozenset({WHITE}),
        "none": frozenset(),
        "both": frozenset({BLACK, WHITE}),
    }[mode]


# ----------------------------------------------------------------- assets
class Assets:
    """The generated art, or ``None`` for anything that will not load."""

    def __init__(self, directory: str = ASSET_DIR) -> None:
        self.directory = directory
        self.board = self._load("board.jpg")
        self.panel = self._load("panel.jpg")
        self.stones = {BLACK: self._load("stone_black.png"),
                       WHITE: self._load("stone_white.png")}
        self.spark = self._load("spark.png")

    def _load(self, name: str):
        path = os.path.join(self.directory, name)
        if not os.path.exists(path):
            return None
        try:
            return arcade.load_texture(path)
        except Exception:  # pragma: no cover - a corrupt file should not be fatal
            return None

    @property
    def complete(self) -> bool:
        return all([self.board, self.panel, self.spark, *self.stones.values()])


# --------------------------------------------------------------- geometry
@dataclass(frozen=True)
class Geometry:
    """Maps board coordinates to pixels.  Row 0 is the top row, as in the ASCII
    board and in ``format_move``, so 'h7' means the same thing everywhere."""

    size: int
    cell: float
    margin: float
    left: float = 0.0
    bottom: float = 0.0

    @property
    def extent(self) -> float:
        return self.cell * (self.size - 1) + 2 * self.margin

    @classmethod
    def fit(cls, size: int, left: float, bottom: float, width: float,
            height: float) -> "Geometry":
        """Largest board that fits the given area, centred inside it."""
        side = max(80.0, min(width, height))
        cell = side / (size - 1 + 1.6)  # 0.8 cell of margin on each side
        geo = cls(size, cell, cell * 0.8)
        return cls(size, cell, cell * 0.8,
                   left + (width - geo.extent) / 2.0,
                   bottom + (height - geo.extent) / 2.0)

    def point(self, row: int, col: int) -> tuple[float, float]:
        return (self.left + self.margin + col * self.cell,
                self.bottom + self.extent - self.margin - row * self.cell)

    def point_of(self, index: int) -> tuple[float, float]:
        return self.point(*divmod(index, self.size))

    def hit(self, x: float, y: float) -> int | None:
        """Board index under the cursor, or None when it is off the grid."""
        col = round((x - self.left - self.margin) / self.cell)
        row = round((self.bottom + self.extent - self.margin - y) / self.cell)
        if not (0 <= row < self.size and 0 <= col < self.size):
            return None
        px, py = self.point(row, col)
        if math.hypot(x - px, y - py) > self.cell * 0.5:
            return None
        return row * self.size + col

    def star_points(self) -> list[tuple[int, int]]:
        n = self.size
        if n >= 13:
            offsets = (3, n // 2, n - 4)
        elif n >= 9:
            offsets = (2, n // 2, n - 3)
        else:
            return [(n // 2, n // 2)]
        return [(r, c) for r in offsets for c in offsets]


def winning_line(board: Board) -> list[int]:
    """The stones that ended the game, so they can be highlighted."""
    if not board.over or board.winner == 0 or not board.moves:
        return []
    last = board.moves[-1]
    size, cells, player = board.size, board.cells, board.winner
    row, col = divmod(last, size)
    for dr, dc in DIRECTIONS:
        line = [last]
        for step in (1, -1):
            r, c = row + dr * step, col + dc * step
            while 0 <= r < size and 0 <= c < size and cells[r * size + c] == player:
                line.append(r * size + c)
                r += dr * step
                c += dc * step
        if len(line) >= board.win_length:
            return sorted(line)
    return []


class TextCache:
    """Reuses ``arcade.Text`` objects -- building them every frame is costly."""

    def __init__(self) -> None:
        self._items: dict[str, arcade.Text] = {}

    def draw(self, key: str, text: str, x: float, y: float, color=TEXT,
             size: float = 12.0, **kwargs) -> None:
        item = self._items.get(key)
        if item is None:
            item = arcade.Text(text, x, y, color, size, **kwargs)
            self._items[key] = item
        else:
            if item.text != text:
                item.text = text
            item.x, item.y = x, y
            item.color = color
        item.draw()


# ----------------------------------------------------------------- window
class OmokWindow(arcade.Window):
    """The board, the side panel, and the glue to the engine thread."""

    def __init__(self, cfg: Config, model_path: str | None = None,
                 simulations: int | None = None, mode: str = "black",
                 opening_plies: int = 2, opening_temperature: float = 0.8,
                 effects: bool = True) -> None:
        size = cfg.game.board_size
        cell = max(26.0, min(46.0, 660.0 / size))
        board_px = cell * (size - 1 + 1.6)
        panel = 330.0
        super().__init__(int(board_px + panel), int(max(board_px, 620)),
                         f"Omok - {cfg.run_name}", resizable=True)
        self.background_color = PANEL_BG

        self.cfg = cfg
        self.board_size = size
        self.simulations = int(simulations or cfg.mcts.simulations)
        self.mode = mode if mode in MODES else "black"
        self.humans = human_colours(self.mode)
        self.opening_plies = opening_plies
        self.opening_temperature = opening_temperature

        self.board = self._new_board()
        self.panel_width = panel
        self.geometry = Geometry.fit(size, 0, 0, self.width - panel, self.height)

        self.engine = Engine(cfg, model_path)
        self.engine.start()
        self.ready = False
        self.info: dict = {}
        self.status = "loading model..."
        self.status_color = TEXT_DIM
        self.paused = False

        self.pending: tuple[int, str] | None = None   # (job, kind)
        self.hover: int | None = None
        self.hints: list[tuple[int, float]] = []
        self.hints_ply = -1
        self.show_hints = True
        self.eval_black: float | None = None
        self.last_search = ""
        self.text = TextCache()

        # -- animation -----------------------------------------------------
        self.effects = effects
        self.assets = Assets()
        self.clock = 0.0
        self.particles = Particles(900)
        self.sparks = arcade.SpriteList(capacity=256)
        self.drops: dict[int, Clip] = {}     # board index -> landing animation
        self.ripples: list[Clip] = []        # data = (x, y, colour)
        self.flash = Clip(0.0)
        self.shake = 0.0
        self.eval_bar = Animated(0.5, 0.55)
        self.progress = Animated(0.0, 0.18, ease_out_quad)
        self.progress_total = 0
        self.win_sweep: Clip | None = None
        self.hint_reveal = Clip(0.0)

    @property
    def panel_left(self) -> float:
        return self.width - self.panel_width

    # -- state -------------------------------------------------------------
    def _new_board(self) -> Board:
        return Board(self.cfg.game.board_size, self.cfg.game.win_length,
                     self.cfg.game.allow_overline)

    def _reset(self, status: str | None = None) -> None:
        self.engine.cancel()
        self.pending = None
        self.progress.set(0.0, snap=True)
        self.hints, self.hints_ply = [], -1
        self.eval_black = None
        self.eval_bar.set(0.5)
        self.last_search = ""
        self.drops.clear()
        self.ripples.clear()
        self.win_sweep = None
        if status:
            self.status, self.status_color = status, TEXT_DIM

    def _side_name(self, colour: int) -> str:
        return "black" if colour == BLACK else "white"

    def _engine_turn(self) -> bool:
        return not self.board.over and self.board.to_move not in self.humans

    def _play(self, move: int) -> None:
        colour = self.board.to_move
        self.board.play(move)
        self._impact(move, colour)
        if self.board.over:
            self.engine.cancel()
            self.pending = None
            self._celebrate()
            if self.board.winner == EMPTY:
                self.status, self.status_color = "draw", TEXT_DIM
            else:
                self.status = f"{self._side_name(self.board.winner)} wins"
                self.status_color = GOOD

    def _submit(self, kind: str) -> None:
        temperature = (self.opening_temperature
                       if kind == "move" and self.board.move_number < self.opening_plies
                       else 0.0)
        job = self.engine.submit(self.board, self.simulations, temperature, kind)
        self.pending = (job, kind)
        self.progress_total = self.simulations
        self.progress.set(0.0, snap=True)

    # -- effects -----------------------------------------------------------
    def _impact(self, move: int, colour: int) -> None:
        """A stone landed: bounce it in, ring the board, throw some sparks."""
        self.drops[move] = Clip(0.34)
        if not self.effects:
            return
        x, y = self.geometry.point_of(move)
        spark = SPARK_BLACK if colour == BLACK else SPARK_WHITE
        cell = self.geometry.cell
        self.ripples.append(Clip(0.55, data=(x, y, spark)))
        self.particles.emit(
            18, x, y, colour=spark, speed=(40.0, 190.0), life=(0.35, 0.7),
            size=(cell * 0.08, cell * 0.22), gravity=90.0, drag=2.6, grow=0.7,
            spread=cell * 0.2)
        self.shake = max(self.shake, 2.4)

    def _celebrate(self) -> None:
        """Game over: sweep the winning line and set off the confetti."""
        line = winning_line(self.board)
        self.win_sweep = Clip(1.6, data=line)
        if not self.effects:
            return
        self.flash = Clip(0.45)
        self.shake = 9.0 if line else 3.0
        cell = self.geometry.cell
        for index in (line or self.board.moves[-1:]):
            x, y = self.geometry.point_of(index)
            for colour in CONFETTI:
                self.particles.emit(
                    9, x, y, colour=colour, speed=(120.0, 460.0), life=(0.9, 1.8),
                    size=(cell * 0.07, cell * 0.2), direction=math.pi / 2,
                    arc=math.pi * 1.1, gravity=420.0, drag=0.9, spin=220.0,
                    grow=0.3, fade=0.6)

    def _scatter(self) -> None:
        """Puff every stone off the board when a new game starts."""
        if not self.effects:
            return
        cell = self.geometry.cell
        for index in range(len(self.board.cells)):
            colour = self.board.cells[index]
            if colour == EMPTY:
                continue
            x, y = self.geometry.point_of(index)
            self.particles.emit(
                4, x, y, colour=SPARK_BLACK if colour == BLACK else SPARK_WHITE,
                speed=(20.0, 90.0), life=(0.3, 0.6), size=(cell * 0.06, cell * 0.16),
                drag=3.0, grow=1.2)

    def _shaken(self) -> Geometry:
        if self.shake <= 0.05:
            return self.geometry
        # Two different frequencies, so it rattles rather than slides.
        dx = math.sin(self.clock * 61.0) * self.shake
        dy = math.cos(self.clock * 47.0) * self.shake
        return replace(self.geometry, left=self.geometry.left + dx,
                       bottom=self.geometry.bottom + dy)

    # -- arcade callbacks --------------------------------------------------
    def on_resize(self, width: int, height: int) -> None:
        super().on_resize(width, height)
        self.panel_width = max(300.0, min(380.0, width * 0.33))
        self.geometry = Geometry.fit(self.board_size, 0, 0,
                                     width - self.panel_width, height)

    def on_update(self, delta_time: float) -> None:
        for event in self.engine.poll():
            self._handle(event)
        if (self.ready and not self.paused and self.pending is None
                and self._engine_turn()):
            self._submit("move")

        dt = min(delta_time, 1 / 20)  # a stalled frame must not teleport anything
        self.clock += dt
        self.eval_bar.update(dt)
        self.progress.update(dt)
        self.hint_reveal.update(dt)
        self.particles.update(dt)
        self.shake *= 0.86 ** (dt * 60.0)
        self.flash.update(dt)
        if self.win_sweep is not None:
            self.win_sweep.update(dt)
        for index in [i for i, clip in self.drops.items() if clip.done]:
            del self.drops[index]
        for clip in self.drops.values():
            clip.update(dt)
        self.ripples = [r for r in self.ripples if r.update(dt)]

    def _handle(self, event: tuple) -> None:
        kind = event[0]
        if kind == "ready":
            self.ready = True
            self.info = event[1]
            self.status, self.status_color = "your move", TEXT_DIM
        elif kind == "error":
            self.status, self.status_color = event[1], WARN
        elif kind == "progress":
            job, done, total = event[1], event[2], event[3]
            if self.pending and job == self.pending[0]:
                self.progress_total = total
                self.progress.set(done / total if total else 0.0)
        elif kind == "result":
            result = event[1]
            if not self.pending or result.job != self.pending[0]:
                return  # a search we already abandoned
            self.pending = None
            sign = 1.0 if self.board.to_move == BLACK else -1.0
            self.eval_black = sign * result.value
            self.eval_bar.set((clamp(self.eval_black, -1.0, 1.0) + 1.0) / 2.0)
            self.hints, self.hints_ply = result.top, result.ply
            self.hint_reveal = Clip(0.45)
            self.last_search = (f"{result.simulations} sims in {result.seconds:.1f}s "
                                f"({result.nps:.0f}/s)")
            if result.kind == "move":
                self._play(result.move)
                if not self.board.over:
                    self.status = f"{self._side_name(self.board.to_move)} to play"
                    self.status_color = TEXT_DIM
            else:
                self.status, self.status_color = "hint ready", ACCENT

    def on_mouse_motion(self, x: float, y: float, dx: float, dy: float) -> None:
        self.hover = self.geometry.hit(x, y)

    def on_mouse_press(self, x: float, y: float, button: int, modifiers: int) -> None:
        if button != arcade.MOUSE_BUTTON_LEFT or self.board.over:
            return
        if self.board.to_move not in self.humans:
            self.status, self.status_color = "not your turn", WARN
            return
        move = self.geometry.hit(x, y)
        if move is None:
            return
        if not self.board.is_legal(move):
            self.status, self.status_color = "occupied", WARN
            return
        if self.pending is not None:  # a hint was still running
            self.engine.cancel()
            self.pending = None
        self._play(move)
        if not self.board.over:
            self.status = f"{self._side_name(self.board.to_move)} to play"
            self.status_color = TEXT_DIM

    def on_key_press(self, symbol: int, modifiers: int) -> None:
        key = arcade.key
        if symbol in (key.ESCAPE, key.Q):
            self.engine.shutdown()
            self.close()
        elif symbol == key.N:
            self._scatter()
            self.board = self._new_board()
            self._reset("new game")
        elif symbol == key.U:
            self._undo()
        elif symbol == key.SPACE:
            if self.ready and not self.board.over and self.pending is None:
                self._submit("move")
        elif symbol == key.H:
            if self.ready and not self.board.over and self.pending is None:
                self._submit("hint")
                self.status, self.status_color = "thinking...", ACCENT
        elif symbol == key.A:
            self.show_hints = not self.show_hints
        elif symbol == key.F:
            self.effects = not self.effects
            if not self.effects:
                self.particles.clear()
                self.ripples.clear()
                self.shake = 0.0
            self.status = f"effects {'on' if self.effects else 'off'}"
            self.status_color = TEXT_DIM
        elif symbol == key.P:
            self.paused = not self.paused
            if self.paused:
                self.engine.cancel()
                self.pending = None
            self.status = "paused" if self.paused else "running"
            self.status_color = WARN if self.paused else TEXT_DIM
        elif symbol == key.S:
            self.mode = MODES[(MODES.index(self.mode) + 1) % len(MODES)]
            self.humans = human_colours(self.mode)
            self.engine.cancel()
            self.pending = None
            self.status, self.status_color = MODE_LABELS[self.mode], TEXT_DIM
        elif symbol in (key.KEY_1, key.KEY_2, key.KEY_3, key.KEY_4):
            level = LEVELS[symbol - key.KEY_1]
            self.simulations = level[2]
            self.engine.cancel()
            self.pending = None
            self.status = f"{level[1]}: {self.simulations} sims/move"
            self.status_color = TEXT_DIM

    def _undo(self) -> None:
        """Take back to the previous position the human is to move in."""
        moves = list(self.board.moves)
        if not moves:
            return
        take = 1
        if self.humans and self.board.to_move in self.humans and len(moves) >= 2:
            take = 2  # undo the engine's reply as well as our own move
        if self.effects:
            cell = self.geometry.cell
            for index in moves[-take:]:
                x, y = self.geometry.point_of(index)
                self.particles.emit(
                    10, x, y, colour=(190, 200, 220), speed=(30.0, 130.0),
                    life=(0.25, 0.5), size=(cell * 0.06, cell * 0.16), drag=3.2,
                    grow=1.4)
        self.board = board_from_moves(moves[:-take], self.board_size,
                                      self.cfg.game.win_length,
                                      self.cfg.game.allow_overline)
        self._reset(f"took back {take} move{'s' if take > 1 else ''}")

    # -- drawing -----------------------------------------------------------
    def on_draw(self) -> None:
        self.clear()
        geo = self._shaken()
        self._draw_board(geo)
        self._draw_hints(geo)
        self._draw_ripples(geo)
        self._draw_stones(geo)
        self._draw_hover(geo)
        self._draw_particles(geo)
        self._draw_panel()
        self._draw_flash()

    def _draw_board(self, geo: Geometry) -> None:
        extent = geo.extent
        if self.assets.board is not None:
            arcade.draw_texture_rect(self.assets.board,
                                     arcade.LBWH(geo.left, geo.bottom, extent, extent))
        else:
            arcade.draw_lrbt_rectangle_filled(geo.left, geo.left + extent, geo.bottom,
                                              geo.bottom + extent, WOOD)
        arcade.draw_lrbt_rectangle_outline(geo.left, geo.left + extent, geo.bottom,
                                           geo.bottom + extent, WOOD_EDGE, 2)
        first_x, first_y = geo.point(self.board_size - 1, 0)
        last_x, last_y = geo.point(0, self.board_size - 1)
        for i in range(self.board_size):
            _, y = geo.point(i, 0)          # row i
            x, _ = geo.point(0, i)          # column i
            arcade.draw_line(first_x, y, last_x, y, GRID, 1.2)
            arcade.draw_line(x, first_y, x, last_y, GRID, 1.2)
        for row, col in geo.star_points():
            x, y = geo.point(row, col)
            arcade.draw_circle_filled(x, y, max(2.0, geo.cell * 0.09), GRID)
        for i in range(self.board_size):
            x, _ = geo.point(0, i)
            _, y = geo.point(i, 0)
            self.text.draw(f"col{i}", chr(ord("a") + i), x, first_y - geo.margin * 0.78,
                           GRID, geo.cell * 0.32, anchor_x="center", font_name=MONO)
            self.text.draw(f"row{i}", str(i), first_x - geo.margin * 0.45, y, GRID,
                           geo.cell * 0.32, anchor_x="right", anchor_y="center",
                           font_name=MONO)

    def _draw_hints(self, geo: Geometry) -> None:
        """Translucent discs on the engine's candidates, revealed in order."""
        if not (self.show_hints and self.hints) or self.hints_ply != self.board.move_number:
            return
        best = max(p for _, p in self.hints)
        reveal = self.hint_reveal.progress
        for rank, (move, prob) in enumerate(self.hints):
            # Stagger: each candidate starts a little after the one above it.
            local = clamp((reveal - rank * 0.08) / 0.35)
            if local <= 0.0:
                continue
            eased = ease_out_back(local) if self.effects else local
            share = prob / best
            x, y = geo.point_of(move)
            breathe = 1.0 + 0.05 * pulse(self.clock, 1.6) if rank == 0 else 1.0
            radius = geo.cell * (0.16 + 0.26 * share ** 0.5) * eased * breathe
            alpha = int((70 + 130 * share) * local)
            arcade.draw_circle_filled(x, y, max(radius, 0.5), (*ACCENT, alpha))
            if rank == 0:
                self.text.draw("hintpct", f"{prob * 100:.0f}", x, y - geo.cell * 0.13,
                               (12, 20, 32), geo.cell * 0.3, anchor_x="center",
                               font_name=MONO)

    def _draw_ripples(self, geo: Geometry) -> None:
        for clip in self.ripples:
            x, y, colour = clip.data
            eased = ease_out_cubic(clip.progress)
            radius = geo.cell * mix(0.35, 1.5, eased)
            alpha = int(180 * (1.0 - clip.progress) ** 2)
            if alpha > 1:
                arcade.draw_circle_outline(x, y, radius, (*colour, alpha),
                                           max(1.0, geo.cell * 0.05 * (1.0 - eased)))

    def _stone_scale(self, index: int) -> tuple[float, float]:
        """(scale, alpha) for a stone, mid-landing or at rest."""
        clip = self.drops.get(index)
        if clip is None or not self.effects:
            return 1.0, 1.0
        t = clip.progress
        # ease_out_back overshoots past 1, which turns into a squash on impact.
        return mix(1.9, 1.0, ease_out_back(t)), clamp(t * 4.0)

    def _draw_stones(self, geo: Geometry) -> None:
        radius = geo.cell * 0.46
        cells = self.board.cells
        last = self.board.moves[-1] if self.board.moves else None
        sweep = self.win_sweep
        line = list(sweep.data) if sweep is not None else []
        for index in range(len(cells)):
            colour = cells[index]
            if colour == EMPTY:
                continue
            x, y = geo.point_of(index)
            scale, alpha = self._stone_scale(index)
            r = radius * scale
            texture = self.assets.stones.get(colour)
            if texture is not None:
                arcade.draw_texture_rect(
                    texture, arcade.XYWH(x + r * 0.10, y - r * 0.12, r * 2, r * 2),
                    color=SHADOW, alpha=int(70 * alpha))
                arcade.draw_texture_rect(texture, arcade.XYWH(x, y, r * 2, r * 2),
                                         alpha=int(255 * alpha))
            else:
                body = BLACK_STONE if colour == BLACK else WHITE_STONE
                arcade.draw_circle_filled(x, y, r, (*body, int(255 * alpha)))
                arcade.draw_circle_outline(x, y, r, STONE_EDGE, 1.2)
            if index in line:
                self._draw_win_marker(x, y, r, line.index(index), len(line), sweep)
            elif index == last and not self.board.over:
                glow = 0.45 + 0.55 * pulse(self.clock, 1.5)
                arcade.draw_circle_outline(x, y, r * 0.55, (*WARN, int(200 * glow)), 2.0)

    def _draw_win_marker(self, x: float, y: float, r: float, rank: int, total: int,
                         sweep: Clip) -> None:
        """A highlight that runs along the winning line, then settles."""
        head = ease_in_out_cubic(sweep.progress) * 1.5 - rank / max(total, 1)
        local = clamp(head / 0.35)
        if local <= 0.0:
            return
        ring = r * mix(1.9, 0.98, ease_out_elastic(local))
        arcade.draw_circle_outline(x, y, ring, (*GOOD, int(255 * local)), 3.0)
        if sweep.done:
            glow = 0.4 + 0.6 * pulse(self.clock, 1.1)
            arcade.draw_circle_outline(x, y, r * 1.06, (*GOOD, int(220 * glow)), 2.0)

    def _draw_hover(self, geo: Geometry) -> None:
        if (self.hover is None or self.board.over
                or self.board.to_move not in self.humans
                or not self.board.is_legal(self.hover)):
            return
        x, y = geo.point_of(self.hover)
        breathe = 0.94 + 0.06 * pulse(self.clock, 1.1)
        r = geo.cell * 0.46 * breathe
        alpha = int(mix(80, 150, pulse(self.clock, 1.1)))
        texture = self.assets.stones.get(self.board.to_move)
        if texture is not None:
            arcade.draw_texture_rect(texture, arcade.XYWH(x, y, r * 2, r * 2), alpha=alpha)
        else:
            body = BLACK_STONE if self.board.to_move == BLACK else WHITE_STONE
            arcade.draw_circle_filled(x, y, r, (*body, alpha))

    def _draw_particles(self, geo: Geometry) -> None:
        count = len(self.particles)
        if count == 0 or self.assets.spark is None:
            return
        xs, ys, radius, alpha, angle, red, green, blue = self.particles.view()
        # The board rattles; the sparks it threw off rattle with it.
        dx, dy = geo.left - self.geometry.left, geo.bottom - self.geometry.bottom
        texture = self.assets.spark
        while len(self.sparks) < count:
            self.sparks.append(arcade.Sprite(texture))
        for i in range(count):
            sprite = self.sparks[i]
            sprite.position = (float(xs[i]) + dx, float(ys[i]) + dy)
            sprite.scale = max(float(radius[i]) * 2.0 / texture.height, 0.001)
            sprite.angle = float(angle[i])
            sprite.color = (int(red[i]), int(green[i]), int(blue[i]),
                            int(clamp(float(alpha[i])) * 255))
            sprite.visible = True
        for i in range(count, len(self.sparks)):
            self.sparks[i].visible = False
        context = self.ctx
        previous = context.blend_func
        context.blend_func = context.BLEND_ADDITIVE
        self.sparks.draw()
        context.blend_func = previous

    def _draw_flash(self) -> None:
        """A white wash over everything at the moment the game is won."""
        if self.flash.done:
            return
        alpha = int(150 * (1.0 - self.flash.progress) ** 2)
        if alpha > 1:
            arcade.draw_lrbt_rectangle_filled(0, self.width, 0, self.height,
                                              (255, 252, 240, alpha))

    # -- panel -------------------------------------------------------------
    def _draw_panel(self) -> None:
        left, right = self.panel_left, self.width
        if self.assets.panel is not None:
            arcade.draw_texture_rect(self.assets.panel,
                                     arcade.LBWH(left, 0, right - left, self.height),
                                     color=PANEL_TINT)
        else:
            arcade.draw_lrbt_rectangle_filled(left, right, 0, self.height, PANEL_BG)
        arcade.draw_line(left, 0, left, self.height, PANEL_RULE, 1)
        x = left + 20
        y = self.height - 34
        step = 18

        self.text.draw("title", "OMOK", x, y, TEXT, 20, bold=True)
        y -= 26
        self.text.draw("run", self.cfg.run_name, x, y, TEXT_DIM, 11, font_name=MONO)
        y -= step

        spec = self.info.get("spec")
        model = str(self.info.get("source", "loading..."))
        if len(model) > 34:
            model = "..." + model[-31:]
        self.text.draw("model", model, x, y, TEXT_DIM, 10, font_name=MONO)
        y -= step
        if spec is not None:
            self.text.draw(
                "net",
                f"{self.info.get('backend', '?')}/{self.info.get('device', '?')}  "
                f"{spec.blocks}x{spec.channels}  {spec.parameter_count() / 1e6:.2f}M",
                x, y, TEXT_DIM, 10, font_name=MONO)
        y -= step + 8

        y = self._draw_rule(x, y, right)
        self.text.draw("mode", MODE_LABELS[self.mode], x, y, TEXT, 12)
        y -= step
        level = next((name for _, name, sims in LEVELS if sims == self.simulations), "custom")
        self.text.draw("sims", f"{self.simulations} sims/move ({level})", x, y,
                       TEXT_DIM, 11, font_name=MONO)
        y -= step + 10

        y = self._draw_eval(x, y, right)
        y = self._draw_thinking(x, y, right)

        y = self._draw_rule(x, y, right)
        turn = ("game over" if self.board.over
                else f"move {self.board.move_number + 1}, "
                     f"{self._side_name(self.board.to_move)} to play")
        self.text.draw("turn", turn, x, y, TEXT, 12)
        y -= step
        self.text.draw("status", self.status, x, y, self.status_color, 11)
        y -= step
        if self.last_search:
            self.text.draw("speed", self.last_search, x, y, TEXT_DIM, 10, font_name=MONO)
        y -= step + 6

        y = self._draw_top_moves(x, y, right)
        y = self._draw_history(x, y)
        self._draw_keys(x)

    def _draw_rule(self, x: float, y: float, right: float) -> float:
        arcade.draw_line(x, y + 14, right - 20, y + 14, PANEL_RULE, 1)
        return y

    def _draw_eval(self, x: float, y: float, right: float) -> float:
        width = right - 20 - x
        arcade.draw_lrbt_rectangle_filled(x, x + width, y - 2, y + 14, (52, 56, 66))
        if self.eval_black is not None:
            share = self.eval_bar.value  # eased, so the bar slides into place
            arcade.draw_lrbt_rectangle_filled(x, x + width * share, y - 2, y + 14,
                                              (18, 18, 22))
            arcade.draw_lrbt_rectangle_filled(x + width * share, x + width, y - 2, y + 14,
                                              (222, 220, 214))
            arcade.draw_line(x + width * share, y - 4, x + width * share, y + 16,
                             ACCENT, 1.5)
            leader = "black" if self.eval_black >= 0 else "white"
            label = f"{leader} {abs(self.eval_black):+.2f}"
        else:
            label = "no evaluation yet"
        arcade.draw_lrbt_rectangle_outline(x, x + width, y - 2, y + 14, PANEL_RULE, 1)
        self.text.draw("evallabel", label, x, y - 20, TEXT_DIM, 10, font_name=MONO)
        return y - 44

    def _draw_thinking(self, x: float, y: float, right: float) -> float:
        if self.pending is None:
            return y
        width = right - 20 - x
        frac = clamp(self.progress.value)
        arcade.draw_lrbt_rectangle_filled(x, x + width, y, y + 6, (44, 48, 58))
        arcade.draw_lrbt_rectangle_filled(x, x + width * frac, y, y + 6, ACCENT)
        kind = "thinking" if self.pending[1] == "move" else "analysing"
        dots = "." * (1 + int(self.clock * 3) % 3)
        done = int(frac * self.progress_total)
        self.text.draw("think", f"{kind}{dots} {done}/{self.progress_total}", x, y - 16,
                       ACCENT, 10, font_name=MONO)
        return y - 34

    def _draw_top_moves(self, x: float, y: float, right: float) -> float:
        if not self.hints:
            return y
        stale = self.hints_ply != self.board.move_number
        self.text.draw("candhead", "candidates" + (" (previous move)" if stale else ""),
                       x, y, TEXT_DIM, 10)
        y -= 17
        width = right - 20 - x
        reveal = self.hint_reveal.progress
        for rank, (move, prob) in enumerate(self.hints[:5]):
            colour = ACCENT if rank == 0 and not stale else TEXT_DIM
            grown = prob * ease_out_cubic(clamp((reveal - rank * 0.06) / 0.4))
            arcade.draw_lrbt_rectangle_filled(x, x + width * grown, y - 3, y + 11,
                                              (40, 60, 84))
            self.text.draw(f"cand{rank}", f"{format_move(move, self.board_size):<4}"
                                          f"{prob * 100:5.1f}%",
                           x + 4, y, colour, 11, font_name=MONO)
            y -= 17
        return y - 8

    def _draw_history(self, x: float, y: float) -> float:
        moves = self.board.moves
        if not moves:
            return y
        self.text.draw("histhead", "moves", x, y, TEXT_DIM, 10)
        y -= 16
        recent = moves[-8:]
        start = len(moves) - len(recent) + 1
        for row in range(0, len(recent), 4):
            chunk = recent[row:row + 4]
            line = "  ".join(f"{start + row + i:>3}.{format_move(m, self.board_size):<4}"
                             for i, m in enumerate(chunk))
            self.text.draw(f"hist{row}", line, x, y, TEXT_DIM, 10, font_name=MONO)
            y -= 15
        return y

    def _draw_keys(self, x: float) -> None:
        lines = ("click  place a stone", "space  engine moves now",
                 "h  hint      a  overlay", "u  undo      n  new game",
                 "s  swap sides   p  pause", "f  effects   1-4  level",
                 "q  quit")
        y = 18 + 14 * (len(lines) - 1)
        for i, line in enumerate(lines):
            self.text.draw(f"key{i}", line, x, y - i * 14, (150, 158, 172), 10,
                           font_name=MONO)


def run_gui(cfg: Config, model_path: str | None = None, simulations: int | None = None,
            human: str = "black", opening_plies: int = 2,
            effects: bool = True) -> None:  # pragma: no cover
    window = OmokWindow(cfg, model_path=model_path, simulations=simulations,
                        mode=human, opening_plies=opening_plies, effects=effects)
    try:
        arcade.run()
    finally:
        window.engine.shutdown()
