/* Omok AI core -- C ABI.
 *
 * Generated by hand from crates/omok-ffi/src/lib.rs; the LuaJIT bindings in
 * lua/omok/core.lua carry the same declarations.  Keep the three in step.
 *
 * Every fallible call reports failure by return value and leaves a message in
 * omok_last_error(), valid until the next failing call on the same thread.
 */
#ifndef OMOK_H
#define OMOK_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OMOK_TOP_MOVES 8

/* cell values */
#define OMOK_EMPTY 0
#define OMOK_BLACK 1
#define OMOK_WHITE 2

typedef struct OmokEngine OmokEngine;
typedef struct OmokGame OmokGame;

typedef struct {
    int   simulations;
    float c_puct;
    float fpu_reduction;
    int   prior_local_radius;
    float temperature;        /* 0 = always the most-visited move */
    int   batch;              /* leaves per network call; 0 keeps the default */
} OmokOptions;

typedef struct {
    int    best_move;
    float  value;             /* side to move's point of view, [-1, 1] */
    int    simulations;
    double seconds;
    int    forced;            /* 1 when a one-ply win/block overrode the search */
    int    top_count;
    int    top_moves[OMOK_TOP_MOVES];
    float  top_probs[OMOK_TOP_MOVES];
} OmokResult;

const char *omok_last_error(void);
const char *omok_version(void);

/* -- game state ------------------------------------------------------ */
OmokGame *omok_game_new(int size, int win_length, int allow_overline);
void      omok_game_free(OmokGame *game);
OmokGame *omok_game_clone(const OmokGame *game);
void      omok_game_reset(OmokGame *game);
int       omok_game_play(OmokGame *game, int index);
int       omok_game_undo(OmokGame *game);
int       omok_game_is_legal(const OmokGame *game, int index);
int       omok_game_size(const OmokGame *game);
int       omok_game_to_move(const OmokGame *game);
int       omok_game_winner(const OmokGame *game);
int       omok_game_is_over(const OmokGame *game);
int       omok_game_move_count(const OmokGame *game);
int       omok_game_move_at(const OmokGame *game, int i);
int       omok_game_last_move(const OmokGame *game);
const unsigned char *omok_game_cells(const OmokGame *game);
int       omok_game_win_line(const OmokGame *game, int *out, int cap);
int       omok_game_forced_move(const OmokGame *game);

/* -- engine ---------------------------------------------------------- */
void      omok_options_default(OmokOptions *out);
OmokEngine *omok_engine_new(const char *model_path, uint64_t seed);
void      omok_engine_free(OmokEngine *engine);
const char *omok_engine_describe(const OmokEngine *engine);
int       omok_engine_board_size(const OmokEngine *engine);

/* Asynchronous: begin, then poll each frame. */
int       omok_search_begin(OmokEngine *engine, const OmokGame *game,
                            const OmokOptions *options);
int       omok_search_poll(OmokEngine *engine, OmokResult *out); /* 1 ready, 0 pending, -1 error */
void      omok_search_cancel(OmokEngine *engine);
int       omok_search_is_running(const OmokEngine *engine);

/* Blocking, for callers with nothing to draw while they wait. */
int       omok_search(OmokEngine *engine, const OmokGame *game,
                      const OmokOptions *options, OmokResult *out);

#ifdef __cplusplus
}
#endif
#endif /* OMOK_H */
